DROP TABLE IF EXISTS users;



CREATE TABLE users(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR (300) NOT NULL DEFAULT "",
last_name VARCHAR (300) NOT NULL DEFAULT "",
email VARCHAR (300) NOT NULL DEFAULT "",
age INT(11) NOT NULL DEFAULT 0,
address VARCHAR (300) NOT NULL DEFAULT "",
is_registered BOOLEAN NOT NULL DEFAULT FALSE,
);
